### ISSUE TITLE
Logo Design for Sharp

### ISSUE THREAD

**Issue by zuurw** [tfiers/sharp#49]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by tfiers** [comment]
Hello Zuur,

Thanks for the proposal. Please go ahead if you'd like.
Here are two posters related to the project, for inspiration:
- https://tomasfiers.net/content/Poster-SWR-NERF-retreat.pdf
- https://tomasfiers.net/content/CNSN-Poster.pdf

Best,
Tomas

**Comment by zuurw** [comment]
Hi @tfiers thanks for all the informations I will start to create some designs and I will send it to you soon.

Greetings-!!!

**Comment by tfiers** [comment]
Hello @zuurw , any news?

**Comment by zuurw** [comment]
Hi Im going to do something this weekend for you.

**Comment by zuurw** [comment]
Hello I made this to this project, I get inspired on the rat and the letter S of sharp. See if you like it, if not I can make other one.

![rata1](https://user-images.githubusercontent.com/40801473/56615706-8bf4d180-6613-11e9-94f5-63c1ca741767.jpg)

**Comment by tfiers** [comment]
Thank you very much! I added the logo to the ReadMe :)
